services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mercuryledger
    ports: ["5441:5432"]
  redis:
    image: redis:7
    ports: ["6401:6379"]
