# Be sure to restart your server when you modify this file.

# This file holds the secret_key_base for the application.
# Rails uses this for signing/encrypting cookies and other security mechanisms.

development:
  secret_key_base: development_secret_key_base_for_taskforge_please_change_in_production_1234567890abcdef

test:
  secret_key_base: test_secret_key_base_for_taskforge_testing_purposes_only_1234567890abcdef1234567890abcdef

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
