services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ironfleet
    ports: ["5443:5432"]
  redis:
    image: redis:7
    ports: ["6403:6379"]
