version: '3.9'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geneforge
    ports: ["5435:5432"]

  redis:
    image: redis:7
    ports: ["6382:6379"]

  nats:
    image: nats:2.10
    command: ["-js"]
    ports: ["4225:4222"]

  etcd:
    image: quay.io/coreos/etcd:v3.5.11
    command: ["etcd", "--advertise-client-urls=http://0.0.0.0:2379", "--listen-client-urls=http://0.0.0.0:2379"]
    ports: ["2382:2379"]

  minio:
    image: minio/minio:latest
    command: server /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: ["9000:9000"]
