spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/docuvault
    username: docuvault
    password: docuvault
  redis:
    host: redis
    port: 6379
  jpa:
    hibernate:
      ddl-auto: create-drop

max:
  file:
    size: "10MB"
